# Generated by Django 3.2.4 on 2021-10-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
