# Generated by Django 3.2.4 on 2021-11-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20211106_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/cart_files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.order')),
            ],
        ),
    ]
