# Generated by Django 3.2.4 on 2021-10-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211012_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
