# Generated by Django 3.2.4 on 2021-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('BT', 'BLUE-THINGS'), ('B', 'BOLTS'), ('C', 'CORDS'), ('P', 'PIPES'), ('R', 'RIVETS'), ('BL', 'BOILERS')], max_length=2)),
                ('status', models.CharField(blank=True, choices=[('A', 'Available'), ('P', 'Pending'), ('N', 'Not available')], max_length=2)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
