# Generated by Django 3.2.4 on 2021-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('GB', 'GAS-BOILERS'), ('EB', 'ELECTRIC-BOILERS'), ('PB', 'PELLET-BOILERS'), ('WH', 'WATER-HEATERS')], max_length=2),
        ),
    ]
