# Generated by Django 3.2.4 on 2021-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211009_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.CharField(blank=True, choices=[('danfoss', 'danfoss')], max_length=20),
        ),
    ]
