# Generated by Django 3.2.4 on 2021-10-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20211015_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Available'), ('P', 'Pending'), ('N', 'Not available')], default='A', max_length=2),
        ),
    ]
