# Generated by Django 3.2.4 on 2021-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20211015_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='article',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
