# Generated by Django 3.2.4 on 2021-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20211015_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
