# Generated by Django 3.2.4 on 2021-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_category_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
