# Generated by Django 3.2.4 on 2021-10-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='landing/static/landing/images/mainpage/default.jpg', upload_to=''),
        ),
    ]
