# Generated by Django 3.2.4 on 2021-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/landing/images/mainpage/default.jpg', upload_to=''),
        ),
    ]
