# Generated by Django 3.2.4 on 2021-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20211023_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='measure_unit',
            field=models.CharField(default='шт.', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
