# Generated by Django 3.2.4 on 2021-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20211101_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
