# Generated by Django 3.2.4 on 2021-11-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_item_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
